project:
  type: website

website:
  title: "Employment Data Explorer (alpha)"
  image: 'https://www.bfi.org.uk/dist/client/0207614d447715c2d2b9.svg'
  # favicon: 'https://www.bfi.org.uk/dist/client/e51a86bb7ce82a9e9741.svg'
  image-alt: Logo of British Film Institute
  open-graph: true
  repo-url: https://github.com/BFI-RSU/employment
  repo-actions: [edit, issue]
  navbar:
    background: "#e50076"
    logo: https://www.bfi.org.uk/dist/client/0207614d447715c2d2b9.svg
    logo-alt: Logo of British Film Institute
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: aps-report.qmd
        text: Employment by Sector
      - href: idbr-report.qmd
        text: Workplaces & Enterprises

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



